### ISSUE TITLE
swoole 和 composer 冲突

### ISSUE THREAD

**Issue by mryfan** [swoole/swoole-src#5213] opened 2023-12-08 09:31 UTC
我尝试了不同办法，当enable-swoole-curl="yes" 后，执行composer require 会出现 “Segmentation fault”
![image](https://github.com/swoole/swoole-src/assets/28995283/8a3359e2-621d-426b-978f-b05d8846e094)
swoole version :5.1.1
php版本:8.3.0
环境:windows docker
![image](https://github.com/swoole/swoole-src/assets/28995283/921005ce-d293-4bf6-8ed4-3634e3c02775)

**Comment by sy-records** [comment] 2023-12-08 12:10
Duplicate of #5206

**Closed by sy-records** 2023-12-08 12:10 UTC
