### ISSUE TITLE
Swoole Tracker3.1发布，支持完善的内存泄漏检测！请问现在找不到Swoole Tracker 下载链接，是不提供该扩展了么？

### ISSUE THREAD

**Issue by mdys** [swoole/swoole-src#5408] opened 2024-07-14 22:36 UTC
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

如题，感谢

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by sy-records** [comment] 2024-07-15 00:20
Duplicate of #5350

**Closed by sy-records** 2024-07-15 00:20 UTC
