### ISSUE TITLE
Debugging Application with Xdebug

### ISSUE THREAD

**Issue by aftabnaveed** [swoole/swoole-src#1681] opened 2018-06-01 05:23 UTC
PHP Version 7.1.9 

The documentation says that Swoole coroutine cannot be used with xdebug, while developling applications  xdebug is very helpful tool. For smaller application it may not be a problem but larger applications makes it necessary to use it.  

My question is how can I debug applications while still using Swoole Coroutines ?

**Comment by matyhtf** [comment] 2018-06-01 08:12
Hi @aftabnaveed , Xdebug conflicts with swoole coroutine.

We are developing a coroutine tracking and debugging tool now. Will be released later

**Comment by aftabnaveed** [comment] 2018-06-01 09:57
When do you think that would be released? Mean whily I am relying on this PHP package https://psysh.org/

**Comment by gouchaoer** [comment] 2018-06-08 07:00
amazing
Is this debug tool compatible with xdebug?
If so, it should be convenient to use it in phpstorm

**Comment by sshymko** [comment] 2018-07-04 00:29
@matyhtf 
Wouldn't it be better to make Swoole and Xdebug compatible instead of creating a custom debug tool? Is it possible at all? Xdebug is a mature tool with excellent IDE support. It does not make sense to create yet another tool.

**Comment by tarach** [comment] 2018-07-06 22:31
@sshymko 
I'm guessing it sounds a lot easier than it actually is unfortunately.

@matyhtf 
Please let us know when there will any alpha even available. I would love to try it. 
~and thanks for swoole btw :)

**Comment by derickr** [comment] 2018-07-09 08:46
If anything, you should probably base any debugging tool off the DBGp protocol, so that at least IDEs have instantaneous support for it, as it's the protocol that Xdebug uses: https://xdebug.org/docs-dbgp.php — feel free to reach out if you have questions regarding the protocol.

**Comment by tarach** [comment] 2018-08-29 17:37
@derickr When you were developing xdebug how were you debugging your extensions? I mean Swoole clearly has a conflict with debuggers. I'm guessing its because they all use the same entrypoint to the PHP/Zend engine. If I were to trace that issue watching line by line PHP startup process ( just like your extension allows me to do with PHP scripts ) what tools should I use?

@matyhtf What kind of approach would you suggest for now? Does register_tick_function would work with Swoole ( I remember using it once or twice for debugging ) or maybe write code compatible with standard stack Apache / Nginx + PHP ?

**Comment by derickr** [comment] 2018-08-29 17:47
@tarach ``export USE_ZEND_ALLOC=0`` && ``export ZEND_DONT_UNLOAD_EXTENSIONS=1``. And then use ``gdb`` as "Xdebug replacement" like ``gdb --args path/to/php script.php`` — it's command line based. You can set break points on functions with ``break functioname`` or ``break filename:linenumber``. The trick is finding out where to set the breakpoint...

For debugging memory leaks and other issues, I'd use ``valgrind``, like ``valgrind php script.php`` (tiny tutorial at https://derickrethans.nl/valgrind-null.html).

**Comment by aftabnaveed** [comment] 2018-10-14 22:35
@matyhtf  Has any progress been made in this regard? We really want to migrate from Swoole 2.0.x to Swoole 4.x but xdebug is a deal breaker for us at the moment.

**Comment by er1z** [comment] 2019-03-13 13:50
Bump? Is this still at least on a roadmap?

**Comment by eugenzaharia** [comment] 2019-04-10 11:05
Any progress to this feature?

**Comment by nick-zh** [comment] 2019-06-06 09:40
Is there a way to disable coroutines? The doc states: https://www.swoole.co.uk/coroutine
But when i do a `./configure --disable-coroutine` i get:
```
configure: WARNING: unrecognized options: --disable-coroutine
```

**Comment by sshymko** [comment] 2019-06-07 05:29
I'm with @nick-zh on providing the ability to disable coroutines for Xdebug compatibility purposes.
In fact, stateful applications with mutable global state cannot utilize coroutines.
Specialized coroutine-aware debugging tool would be irrelevant to them.

**Comment by nick-zh** [comment] 2019-07-03 05:59
Anybody interested in using xdebug (only if you are not using coroutines), check out this issue:
https://github.com/swoole/swoole-src/issues/2655
Thx again @mabu233

**Comment by lihe6666** [comment] 2020-03-24 16:53
Any progress to this feature?

**Comment by nick-zh** [comment] 2020-03-25 05:37
@lihe6666 are you having trouble using https://github.com/swoole/sdebug ?
The newest release / branch should also work with `php:7.4`

**Comment by aftabnaveed** [comment] 2020-03-25 06:11
@nick-zh the documentation seems to be not very clear about it, what does it do? Does it replace xdebug? Does it support co-routines?

**Comment by nick-zh** [comment] 2020-03-25 06:29
@aftabnaveed it does replace xdebug if you are using swoole, yes. As to co-routines, i can't say since i don't use them, sry. If you find out, please let us know :v:

**Comment by huanghantao** [comment] 2020-03-25 06:32
@aftabnaveed Have you ever used xdebug? Sdebug is installed exactly the same way as xdebug. Perhaps you could first see how xdebug is used?

```bash
[root@592b0366acbf ~]# cat /etc/php.d/sdebug.ini
zend_extension=xdebug.so
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
[root@592b0366acbf ~]#
```

**Comment by lihe6666** [comment] 2020-04-04 06:00
> https://github.com/swoole/sdebug

Think you.

**Comment by juslintek** [comment] 2020-06-08 10:22
Seems like this is not working with IDE Key.
```
xdebug support => enabled
Support Xdebug on Patreon, GitHub, or as a business: https://xdebug.org/support
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => /tmp => /tmp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => DOCKER-MYG2-BACKEND => DOCKER-MYG2-BACKEND
xdebug.max_nesting_level => 500 => 500
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => On => On
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /var/www/html/storage/cache/xdebug-profiles/ => /var/www/html/storage/cache/xdebug-profiles/
xdebug.profiler_output_name => cachegrind.out.%R.%p => cachegrind.out.%R.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_host => host.docker.internal => host.docker.internal
xdebug.remote_log => no value => no value
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
```

**Comment by nick-zh** [comment] 2020-06-08 10:40
@juslintek just to make sure, you are using [sdebug](https://github.com/swoole/sdebug) with the branch `sdebug_2_9`?

**Comment by juslintek** [comment] 2020-06-08 11:14
@nick-zh I am using it, the thing is if I run sdebug.
![image](https://user-images.githubusercontent.com/5687423/84024080-e70d9300-a991-11ea-8709-a86ec1697500.png)
If I set breakpoint lets to say at Authentication controller to check if it is fetching fresh request or one from memory. And I restart the whole server and it is not even starting it is stuck. Then I stop it and it starts. But after it starts if I run remote debug again it has no effect no matter how many requests I make, the breakpoint is never hit, even though that part I breakpoint is checked via middleware every request. With php-fpm it worked. With swoole and sdebug it doesn't.

I removed xdebug, because it was crashing my whole PC. :D

**Comment by nick-zh** [comment] 2020-06-08 11:27
@juslintek alright thx, i will try to check this evening in a small test project if i can reproduce this. Have to be honest, didn't have to debug for a few weeks. But apart from getting it runnig for the first time, i had no problems.

**Comment by juslintek** [comment] 2020-06-08 12:03
@nick-zh, well I'm using it inside a docker, maybe I should've mentioned that. :-)
it is the latest ubuntu lt is, with the latest PHP 7.4.

**Comment by nick-zh** [comment] 2020-06-08 12:50
@juslintek yeah i figured and you are running osx on host, i noticed the `host.docker.internal` :wink:

**Comment by juslintek** [comment] 2020-06-09 20:58
@nick-zh Yes, I am, but I resolve that manually, that hostname points to the default gateway.

**Comment by pavrip** [comment] 2020-07-26 16:17
So its 2020 now and apparently there is still no proper compatibility with Xdebug?
I have just managed to install Swoole after a nightmare because of the terrible documentation and now I am still getting the same issue,
I am trying to build a fantastic framework and I would love to build it on top of Swoole, but its very hard without a proper debugging tool

**Comment by huanghantao** [comment] 2020-07-27 01:16
@pavrip 

Can you use this? If there is a problem, I will try to solve it:

https://github.com/huanghantao/xdebug

**Comment by nick-zh** [comment] 2020-07-27 05:32
@juslintek @pavrip sry guys i totally forgot to provide my findings. So this seems to work fine with the current sdebug version on `swoole:4.5.2`
i am using the following xdebug.ini settings:
```
zend_extension=xdebug.so
xdebug.profiler_enable_trigger=1
xdebug.remote_enable=on
xdebug.remote_autostart=off
xdebug.remote_connect_back=1
xdebug.idekey=PHPSTORM
```
Also you need to run the debug target in PHPStorm, before you start swoole. It seems if you start the debug target when swoole is already running, it doesn't work properly, at least for me.

@huanghantao if you have any improvements to sdebug, a PR to `swoole/sdebug` would be highly appreciated

**Comment by huanghantao** [comment] 2020-12-14 10:02
We recommend using https://github.com/swoole/yasd to debug

**Closed by huanghantao** 2020-12-14 10:02 UTC
Labels: Incompatibility, coroutine, question

**Comment by juber-ivre** [comment] 2021-01-18 18:58
@juslintek any luck on this? I'm also using laravel-s on a docker setup but unable to debug. Communication between container and IDE seems fine and even seems to start to capture something but it drops after a second or so.

**Comment by juslintek** [comment] 2021-02-22 09:20
@juber-ivre it works randomly, you have to restart docker container or process or restart it, make sure no parallel connections exist and make sure ide accepts more then 4 xdebug connections. But usually what I do is just replay specific request from developer tools network tab. With phpunit there are no problems :-)

**Comment by juslintek** [comment] 2021-02-22 10:23
> We recommend using https://github.com/swoole/yasd to debug

It doesn't work with phpstorm, even tests fail. Left a issue regarding that: https://github.com/swoole/yasd/issues/95 as I see it doesn't work with VSCode as well: https://github.com/swoole/yasd/issues/94

And Sdebug does not support php8 :-( Its like a dead end. You have to fall back to cli coding... Thats a bad dev experience.

**Comment by Radiergummi** [comment] 2022-06-07 09:14
Any news on this front? Ditching XDebug is simply not an option. No other tool is going to get as much traction and IDE support. This is a show stopper...

**Comment by aftabnaveed** [comment] 2022-06-07 10:22
> Any news on this front? Ditching XDebug is simply not an option. No other tool is going to get as much traction and IDE support. This is a show stopper...

If you don't need the coroutines just disable it while debugging and the xdebug should work perfectly fine.

**Comment by Radiergummi** [comment] 2022-06-08 15:38
> If you don't need the coroutines just disable it while debugging and the xdebug should work perfectly fine.

No, it doesn't, sadly. We're running Laravel Octane on Swoole and XDebug won't connect to the IDE if running in Swoole. We had to build an awkward workaround to use the builtin PHP server in local development instead of Octane to be able to debug our application.

**Comment by nprasath002** [comment] 2023-12-18 08:38
Hi @Radiergummi ,
Sorry for reopening this conversation. But I am curious about what workaround you use to get xdebug working?

**Comment by Radiergummi** [comment] 2023-12-18 09:41
No worries @nprasath002. So what we do is a bit awkward, but works: Basically, we use the built-in PHP web server instead of Octane/Swoole in locale development. That is, our entry point script checks the configured environment and either spawns `php artisan octane:start` in production, or `php artisan serve` in local development.  
This allows us to use XDebug locally -- by simply not serving with Swoole. That carries the risk of not noticing a certain kind of bugs or memory leaks; that's another reason to have a rigorous testing schedule, and a staging environment, though.

I'd very much prefer XDebug to work in Swoole, but that's how it is right now.

**Comment by nprasath002** [comment] 2023-12-19 06:22
Thanks @Radiergummi

**Comment by alex-lx** [comment] 2024-01-12 03:42
Hi, any progress here? Our project uses coroutine, so not using swoole in dev is not a option.:-)

**Comment by Radiergummi** [comment] 2024-01-12 16:09
> Hi, any progress here? Our project uses coroutine, so not using swoole in dev is not a option.:-)

I know this sounds stupid, but you're probably better off wrapping that code in an `if ($dev)` block and run it synchronously. If debugger support lands in Swoole at all, it's a long way off, and you probably will need your debugger until then...
